### ISSUE TITLE
Exclude org.apache.http.HttpStatus from SDK

### ISSUE THREAD

**Issue by isabsent** [box/box-android-sdk#104]
As I know, org.apache.http package was removed from Android API 23 (6.0 - Marshmallow). You are using **org.apache.http.HttpStatus** constants in the SDK. It is insufficient usage and can be easily omitted.

**Comment by doncung** [comment]
Thanks we are currently working on a major release which will no longer use HttpStatus and will improve parsing performance.  It is breaking change however so there will be some minor code changes that will be necessary to use the new release (currently it's on the ChangeJsonParser branch). I'll update once we have officially released and made the necessary changes to the other sdks.

**Comment by doncung** [comment]
For now please use: 
https://github.com/box/box-android-sdk/tree/baymax
We have released our official Box app using this version of the SDK. We'll merge to master and push to Maven once we've done cleanup.

**Comment by yashdsaraf** [comment]
I'm making an app based on box content api targeting api __23__, should I use the source from __master__ branch or __baymax__? As both have been recently updated.
