### ISSUE TITLE
Direct download link is necessary.

### ISSUE THREAD

**Issue by isabsent** [box/box-android-sdk#112]
Your [Android Box app](https://play.google.com/store/apps/details?id=com.box.android) has no "Send file" option, just a [Share](https://cloud.githubusercontent.com/assets/4918293/13560942/30ad16ae-e450-11e5-987e-14144a471596.png) option, wich give us a link to a **preview page** in a browser. My aim is to give user an opportunity to download file, shared from your Android Box app in my Android app, directly and I need to get a **direct download** link for this purpose or convert your **share** link to **direct download** link. Such method doesn't exist [as I know](http://stackoverflow.com/a/12843924/753575) in your documentation.

Dropbox, Google Drive, OneDrive do not have such a method too, but they all have simple way to convert **share** link to **direct download** link [manipulating](http://www.technorange.com/cloudlinker-direct-link-generator-for-dropboxgoogle-driveone-drive-copy-com/) with parts of **share** link. 

Is it possible to make the same with your **share** link? If no what do you recommend to fulfill my requirements?

**Comment by doncung** [comment]
The market android app has a "open in" feature that will download a file and then launch an intent to open it in another application providing the content as file:// and has a mime type based on the file extension. If your application has the corresponding intent filter your users can choose your application to handle that intent. 

As for downloading the shared link, you will need your own access token. With your access token you can make a request to get the content from the shared link (BoxApiShare.getSharedLinkRequest). 
Once you know what the contents of the shared link are you can download those contents normally by using a BoxSharedLinkSession.
