### ISSUE TITLE
Error message when granting access to Box account

### ISSUE THREAD

**Issue by mdobric** [box/box-android-sdk#129]
When using the SDK to grant access to a Box account on Android, the attached error message pops up. This only happens when the official Box app is also installed on the device. The device log shows this error:

W/ActivityManager: Duplicate finish request for ActivityRecord{424435c0 u0 com.box.android/.activities.login.BoxThirdPartyAuthenticatorActivity t46 f}

![boxerror](https://cloud.githubusercontent.com/assets/1205366/14329884/9c99f60c-fc0b-11e5-8d38-098f20ca1757.png)

**Comment by paragchandra** [comment]
This can be reproduced with the sample app which comes with the SDK.

**Comment by doncung** [comment]
I'm having some trouble reproducing this. When are you getting this error? Are you entering in the wrong login/password? What are the steps before this? 

Can you check to see if BoxConfig.ENABLE_BOX_APP_AUTHENTICATION  is set to false? This should be the default setting and if enabled should not make the call to the Box app at all. We are in the process of updating the current application and when we can improve the experience we will update the default.

**Comment by mdobric** [comment]
This doesn't seem to be happening anymore with the latest Dropbox app.

**Comment by doncung** [comment]
Please try with the latest sdk. We have fixed a number of issues of which I believe this is one.
