### ISSUE TITLE
Send non-file parts first in BoxMultipartRequest

### ISSUE THREAD

**Issue by klk-** [box/box-android-sdk#133]
This is in accordance with Box API recommendation.

From https://box-content.readme.io/reference#upload-a-file:
"Note that the file bytes should come after the JSON for best
performance."

**Comment by xiaodongw** [comment]
I created a pull request for this issue: https://github.com/box/box-android-sdk/pull/202

**Comment by doncung** [comment]
Thanks. That logic is now part of the latest master.
