### ISSUE TITLE
Refreshing task not removed from BoxAuthentication.mRefreshingTasks when exception occurs in doRefresh()

### ISSUE THREAD

**Issue by mdobric** [box/box-android-sdk#135]
The refreshing task for a user is not removed from the map of tasks (BoxAuthentication.mRefreshingTasks) if an exception occurs when sending the request (see BoxAuthentication.java, lines 353-358, git tag v3.0.3). For example, if a refresh request is issued while there is no network connectivity, then subsequent requests for the same user will fail even if network connectivity has been restored.

**Comment by doncung** [comment]
Thanks for letting us know. I've merged a fix for that.
