### ISSUE TITLE
Create BoxSession with only AccessToken

### ISSUE THREAD

**Issue by JaredBanyard** [box/box-android-sdk#18]
If we are managing the authentication ourselves, how can we create a BoxSession with just the access token?

**Comment by doncung** [comment]
Hi Jared,

I'm tackling just that issue now. I have some code that should be working, but which I'd like to test internally for a while before merging. If you are interested you can try it out yourself, and I'd be happy to address any issues you encounter while doing so.
Here's the branch with the code:
https://github.com/box/box-android-sdk/tree/CustomAuthentication

Don

**Comment by doncung** [comment]
The custom auth logic has been merged into master.

**Comment by JaredBanyard** [comment]
Too late, already implemented the UI ourselves ;)  Thanks though!
