### ISSUE TITLE
Box content sdk authentication failed error

### ISSUE THREAD

**Issue by ashishparmar** [box/box-android-sdk#183]
I have used box content sdk for integration in my application .I entered email address and password correctly and I got logged in successfully and sdk display grand access page to allow me to grand access but when I click on grand access button I got authentication failed error every time.

I got following error with protocol number :

TYPE_WEB_ERROR﹕ Authentication Failed
Details: -10 The protocol isn't supported.
Kindly help me if anyone has an idea on this.

Thank you in advanced!!

**Comment by doncung** [comment]
Where are you seeing that error?  Is it from logcat? 
If so can you post the original stacktrace?

**Comment by ashishparmar** [comment]
I can access login screen easily :+1: 


![grand_access](https://cloud.githubusercontent.com/assets/6857486/17268964/dfde9150-5658-11e6-9a6a-d11935e9406b.PNG)
After login screen i got below screen:
![grand_access - copy](https://cloud.githubusercontent.com/assets/6857486/17268970/fc1926dc-5658-11e6-8694-52aea4078bc4.PNG)

on grand access button i got the failed authentication error as i post the error code

**Comment by doncung** [comment]
I see thanks.  I think the error is happening inside the webview for some reason possibly device or network specific. 
Can you try cloning the repo and adding some logging or breakpoint to the onReceivedError logic in the OauthWebView? What I'm looking for is the "failingUrl" for that error code and description.

**Comment by ashishparmar** [comment]
I could not found the any log during the logging , but I am surprised to suddenly break down this sdk for android , even it is work in iOS , So what is the problem ,can you please suggest the new sdk version or can you reference new working demo?

**Comment by doncung** [comment]
Which branch/ version are you using? You can try the baymax branch which we are using in our official application, but very little of the auth logic has changed. Protocol isn't supported would indicate somehow there is a weird redirect to an unrecognized authority. Speaking of which, what is the redirect url  you are using?

**Comment by ashishparmar** [comment]
I am using master branch but today I have noticed that "Updated 2 days ago by doncung" . So , is  this updated master branch  completed version? 

And I am using "boxsdk-<cliend_id>://boxsdkoauth2redirect" redirect_url  like in iOS use.
can you please explain if  I am not going to use "Redirect Url" than what's the problem will occur?

**Comment by doncung** [comment]
I see that is probably the reason. Android's webview doesn't recognize the boxsdk-:// authority so it is treating that as an error. Please try using https:// as the authority.  
You can also potentially override shouldOverrideUrlLoading to intercept the custom authority before it gets to the error logic, but I would recommend the former.

**Comment by ashishparmar** [comment]
Thank you for the answer . But Can you please explain what shout be right for generate " https:// " as redirect URL. Some example ?  My question is that what should be there?

**Comment by doncung** [comment]
We suggest the default:
https://app.box.com/static/sync_redirect.html
If you have your own server page you can also use that, but  the user will only be navigated there very briefly.

**Comment by doncung** [comment]
Closing this as it should be resolved, please create a new issue if there are issues after changing the redirect.

**Comment by paragchandra** [comment]
I'm seeing the same issue, on the "baymax" branch. What am I supposed to use for the redirect URL? I have tried the default you suggested, literally "https://app.box.com/static/sync_redirect.html". That does not work - I get a "There seems to be a problem with this app" error page. Likewise, I have tried changing the "boxsdk-xxxx://" portion to "https-xxxx://", but no dice.
