### ISSUE TITLE
How to get access token from JSON

### ISSUE THREAD

**Issue by Ankurjain30** [box/box-android-sdk#223]
I am using your code to create box session but getting warning of unhandled JSON members. pls gudie how to handle them.

  boxSession = new BoxSession(mycontext);
        boxSession.authenticate();

**Comment by doncung** [comment]
Are you seeing this warning in the sample application? Can you post the log where you are seeing this?
Generally you should not need to handle the access token or json parsing yourself as this should be taken care of for you. Please keep in mind that boxSession.authenticate() is asynchronous and so you will need to either assign a listener to wait or block till the user has gone through the login flow.

**Comment by doncung** [comment]
I'll close for now. Please create a new issue if you are continuing to see this issue.
