### ISSUE TITLE
Repeatedly logging out/in will cause Box's WebView to fail to load

### ISSUE THREAD

**Issue by paragchandra** [box/box-android-sdk#226]
During testing, I need to log in and out of different Box accounts frequently, and the behavior I see when doing this is that quite often Box's WebView, the one that asks for the username and password, will fail to load after a few iterations of this. I have been able to reproduce this with the box-content-sample application, on the master branch. Simply:

1. Start the app, login to an account, let the root folder display
2. Select "Log out" from the menu
3. Select "Log in" from the menu
4. Use the same account credentials as before, let the root folder display

Repeat steps 2-4 a few times in rapid succession, and observe that eventually, the Box SDK's WebView will fail to display after selecting "Log in". Sometimes it happens in as few as 3 attempts, other times it can take 7 or more. The only way to log back in to an account is to kill the app and restart it.

I've seen this behavior on:

Nexus 6, running Android 6.0.1
x86 emulator, running Android 6.0
x86 emulator, running Android 4.4

**Comment by paragchandra** [comment]
I enabled both BoxConfig.IS_LOG_ENABLED and BoxConfig.IS_DEBUG and retried my steps. What actually appears to be happening is that the logout API call, https://api.box.com/oauth2/revoke, doesn't occur after I invoke BoxSession.logout(). Once that POST request fails to initiate, then no subsequent request is initiated either.

**Comment by paragchandra** [comment]
I rolled back to v3.0.3 of the Box SDK, and these problems are not present in that older version.

**Comment by paragchandra** [comment]
By "rapid succession" I simply mean do it a few times in a row, without pausing in between each attempt.

**Comment by paragchandra** [comment]
I should also point out that it's not always the BoxSession.logout() call that gets stuck. Sometimes it is the corresponding signin() call. Essentially it seems as if whatever is responsible for dispatching asynchronous network requests gets stuck at some point and stops dispatching them - perhaps a deadlock of some sort?

**Comment by doncung** [comment]
Thanks. I believe I've fixed this issue with this pull request. If you are able to please give it a try, otherwise once one of my coworkers approves we'll merge this in and push an update to maven.
https://github.com/box/box-android-sdk/pull/234

**Comment by doncung** [comment]
The change has been released on maven as 4.03, please let me know if you are experiencing any of these issues with that. If not I'll close these issues.

**Comment by paragchandra** [comment]
I'll give it a try and report back soon

**Comment by paragchandra** [comment]
This seems to be fixed in 4.0.4
