### ISSUE TITLE
Why are there no new tags beyond 3.0.3?

### ISSUE THREAD

**Issue by paragchandra** [box/box-android-sdk#240]
I would like to use v4.0.4 of the SDK, but I must make a small change to the source that is very unlikely to be accepted upstream - it has to do with bypassing the UNKNOWN_URL_SCHEME error. How can I be sure to get this exact version of the source code in the absence of a tag for this version?

**Comment by rgcorrea** [comment]
Hi, We've just pushed a new tag on the latest code.
Thanks for the heads up.

**Comment by paragchandra** [comment]
Thank you. Would it be possible to retroactively tag the prior releases as well?
