### ISSUE TITLE
OAuthActivity leaked.

### ISSUE THREAD

**Issue by isabsent** [box/box-android-sdk#244]
After authentication [Leak Canary](https://github.com/square/leakcanary) shows:

    D/LeakCanary: * com.box.androidsdk.content.auth.OAuthActivity has leaked:
    D/LeakCanary: * GC ROOT org.chromium.content.browser.input.PopupTouchHandleDrawable.mContext
    D/LeakCanary: * leaks com.box.androidsdk.content.auth.OAuthActivity instance
![box_leak](https://cloud.githubusercontent.com/assets/4918293/22591383/d65d0a58-ea46-11e6-9b7f-871d651f0451.png)

I am using BoxActivity to authenticate user:

    public class BoxActivity extends Activity {
        private static final String TAG = "BoxActivity", OAUTH_2 = "oauth2:";
    
        // Replace this with your app key and secret assigned by Dropbox.
        // Note that this is a really insecure way to do this, and you shouldn't
        // ship code which contains your key & secret in such an obvious way.
        // Obfuscation is good.
    
        public final static String
                ACCESS_KEY_NAME = "ACCESS_KEY_BOX",
                ACCESS_SECRET_NAME = "ACCESS_SECRET_BOX";
        private Button mSubmit;
        private BoxSession mSession = null, mOldSession = null;
    
        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.activity_box);
    
            BoxConfig.IS_LOG_ENABLED = true;
            BoxConfig.CLIENT_ID = "********************************";
            BoxConfig.CLIENT_SECRET = "*********************************";
            BoxConfig.REDIRECT_URL = "http://127.0.0.1"; // needs to match redirect uri in developer settings if set.
    
            mSubmit = (Button) findViewById(R.id.auth_button);
            mSubmit.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    mSession = new BoxSession(getApplicationContext());
                    mSession.setSessionAuthListener(new BoxAuthListener(BoxActivity.this, mSession, mOldSession));
                    mSession.authenticate();
                }
            });
        }
    
        /**
         * Shows keeping the access keys returned from Trusted Authenticator in a local
         * store, rather than storing user name & password, and re-authenticating each
         * time (which is not to be done, ever).
         */
        public void storeAuth(String oauth2AccessToken) {// Store the OAuth 2 access token, if there is one.
            if (oauth2AccessToken != null) {
                SharedPreferences prefs = MyApplication.getAccountPreferences(this);
                SharedPreferences.Editor edit = prefs.edit();
                edit.putString(ACCESS_KEY_NAME, OAUTH_2);
                edit.putString(ACCESS_SECRET_NAME, oauth2AccessToken);
                edit.commit();
            }
        }
    }
with

    public class BoxAuthListener implements BoxAuthentication.AuthListener {
        private BoxActivity ba;
        private BoxSession mSession, mOldSession;
    
        public BoxAuthListener(BoxActivity ba, BoxSession session, BoxSession oldSession) {
            this.ba = ba;
            mSession = session;
            mOldSession = oldSession;
        }
    
        @Override
        public void onAuthCreated(BoxAuthentication.BoxAuthenticationInfo info) {
            ba.storeAuth(info.accessToken());
            Clouds.BOX.getBox().setService(mSession);
            ba.setResult(Activity.RESULT_OK);
            ba.finish();
            ba = null;
        }
    
        @Override
        public void onAuthFailure(BoxAuthentication.BoxAuthenticationInfo info, Exception ex) {
            if (ex != null) {
    //            clearAdapter();
            } else if (info == null && mOldSession != null) {
                mSession = mOldSession;
                mOldSession = null;
                onAuthCreated(mSession.getAuthInfo());
            }
        }
    
        @Override
        public void onRefreshed(BoxAuthentication.BoxAuthenticationInfo info) {
            String accessToken = info.accessToken();
            ba.storeAuth(accessToken);
        }
    
        @Override
        public void onLoggedOut(BoxAuthentication.BoxAuthenticationInfo info, Exception ex) {
    //        clearAdapter();
        }
    }
The same leak was observed [here.](https://github.com/vickychijwani/quill/issues/75#issue-90230184)

**Comment by doncung** [comment]
Thanks. I had thought Android had fixed this issue by now, but looks like some work arounds are still necessary. I'll look into it.

**Comment by PreciselyAlyss** [comment]
Fixed by [PR#256](https://github.com/box/box-android-sdk/pull/256)
