### ISSUE TITLE
BoxSession.refresh should not use AsyncTask

### ISSUE THREAD

**Issue by jefftharris** [box/box-android-sdk#248]
If the Box API is being called from an AsyncTask and a refresh is required, the original call will hang until a timeout occurs.  The refresh hangs as AsyncTasks are not processed in parallel by default.  Overriding BoxSession.refresh and using a Thread instead of AsyncTask like the logout() method allows the refresh to occur and the original call to succeed.

**Comment by doncung** [comment]
Thanks Jeff. I'll  look into this.

**Comment by doncung** [comment]
Once this: https://github.com/box/box-android-sdk/pull/251
is merged we'll push a new change to maven. Thanks for pointing this out.

**Comment by jefftharris** [comment]
The issue seems to be fixed with 4.0.6. Thanks for update.
