### ISSUE TITLE
BoxSession multiple instance + onAuthCreated calls

### ISSUE THREAD

**Issue by kkontus** [box/box-android-sdk#250]
Hi

I have an issue with onAuthCreated called multiple times in case where Box login is in the separate activity. There are two workflows tested for login and logout as shown below:

1) MainActivity ---> BoxActivity (login pressed, then right after that log out button pressed, and then login again without going back to MainActivity)    // works fine

2) MainActivity ---> BoxActivity (login and then logout button pressed, without login again) ---> MainActivity ---> BoxActivity (login button pressed sometimes works, sometimes need to be pressed twice to show Box authentication form)

after that when Login button is pressed again onAuthCreate is called multiple times (like for every BoxSession created)

After that I tried a different approach, instead of creating new BoxSession inside initSession() I created a new BoxSession inside my Application class (so we have single BoxSession instance) and then everything worked fine. 
So I'm thinking that there might be an issue with BoxSession instance, it's either not removed on logout or something else, but it looks like there are multiple BoxSession instances and that is way logout doesn't work each time. 

Please correct me if I'm wrong, and tell me if there are any downsides of using single BoxSession instance.

Code that I change is here:

```
public class MyTestApplication extends Application {
    public static BoxSession mSession = null;

    @Override
    public void onCreate() {
        // TODO Auto-generated method stub
        super.onCreate();

        BoxConfig.CLIENT_ID = "xxxxxxx";
        BoxConfig.CLIENT_SECRET = "xxxxxxxxxx";
        // must match the redirect_uri set in your developer account if one has been set. Redirect uri should not be of type file:// or content://.
        BoxConfig.REDIRECT_URL = "http://localhost";

        mSession = new BoxSession(getApplicationContext());
    }
}
``` 
Then in BoxActivity 
```
public class BoxActivity extends AppCompatActivity implements BoxAuthentication.AuthListener {
    public static final String TAG = "BoxActivity";

    // this is the important part
    BoxSession mSession = MyTestApplication.mSession;

.
.
.

    private void initSession() {
        // this is the important part
        //mSession = new BoxSession(this);
        mSession.setSessionAuthListener(this);
        mSession.authenticate(this);
    }
}
```

**Comment by doncung** [comment]
Every session can have their own auth listener. When an authentication
occurs anywhere that effects them they will be notified assuming they are
still in memory.
In your example you are using the same listener, and so it is notified for
as many sessions as are still in memory. If creating a completely new
session you can null out the listener on the previous session. Eventually
it should be garbage collected if there are no references.

PS: You should remove the id and secret as well as update them from the dev
console.

**Comment by kkontus** [comment]
Thank you, I'll try to fix that as you said. 
Oh, thank you, I forgot to remove the id-s, I will change them right away.

Thank you

**Comment by kkontus** [comment]
It's seems it works ok with your suggestions, thank you. We can now close this issue.
