### ISSUE TITLE
How to request contents of folder with additional attributes?

### ISSUE THREAD

**Issue by dse-phongth** [box/box-android-sdk#255]
Hi all,

I want to request the contents of a folder with the size attribute, but I'm not seeing a way to make this request with the `BoxApiFolder` class; `getFolderWithAllItems` and `getItemsRequest` both seem to return objects in mini format.

Thank you in advance for the assistance.

*Edit: Just noticed I'm still on 4.0.1; will try updating to 4.0.6 and see if that changes anything.*

**Comment by doncung** [comment]
You can use the setFields method to request the attributes you need.

**Comment by dse-phongth** [comment]
Oh wow. Thanks.
