### ISSUE TITLE
delete a box folder?

### ISSUE THREAD

**Issue by bezhilarasan** [box/box-android-sdk#264]
i tried to delete a empty box folder using below code

folderApi.getDeleteRequest("folderId")
        // Optional: By default the folder will be deleted including all the files/folders within.
        // Set 'recursive' to false to only allow for the deletion if the folder is empty.
        .setRecursive(false)
        .send();

 i am getting error like com.box.androidsdk.content.BoxException: unexpected exception ?
like  access$900 
folder id is correct!

how can i acheive this

**Comment by doncung** [comment]
So I did a quick try, and I'm unable to reproduce. Can you enable debugging using (use BoxConfig.IS_DEBUG) and paste out the response you are getting? Please don't include an access token. I'm mainly interested in the actual error info. Should look something like this in your logcat:

03-23 16:03:34.698 22583-22688/com.box.android I/BoxContentSdk: Response (400):  {"type":"error","status":400,"code":"folder_not_empty","help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"Cannot delete - folder not empty","request_id":"51431394858d45446d429c"}
03-23 16:03:34.700 22583-22777/com.box.android I/JobItemJsonEntity: Level DB putting key jobitem://DeleteTask/1490310214545_4 with val: {"type":"DeleteTask","id":"1490310214545_4","mCurrentState":"completed","mItemId":"17361948148","mItemType":"folder"}
