### ISSUE TITLE
How to get file/folder size and modified date

### ISSUE THREAD

**Issue by niranjansheshadri** [box/box-android-sdk#268]
Hello,

I tried to get the size and modified date of file/folder using the below code but in return null.

if (item instanceof BoxFolder) {
        BoxFolder folder = (BoxFolder) item;
        long folderSize = folder.getSize();
}

Can anyone help me to solve this issue.

Thank you.

**Comment by doncung** [comment]
That should work, but how are you getting the initial item? If you using
setFields you must provide all fields you want back.

**Comment by niranjansheshadri** [comment]
Thanks for the response.

This is what i am doing 
I have listview and an adapter i am adding the folder items to adapter.

final BoxIteratorItems folderItems = mFolderApi.getItemsRequest(BoxConstants.ROOT_FOLDER_ID).send();

 for (BoxItem boxItem : folderItems) {
    mAdapter.add(boxItem);
}

And in my adapter i using this 

BoxItem item = getItem(position);

if (item instanceof BoxFolder) {
BoxFolder folder = (BoxFolder) item;
long folderSize = folder.getSize();
}

**Comment by doncung** [comment]
Thanks. So I gave this a quick try. It looks like size is not included in the default response from the items request from the server though size and modified date are included for the folder info(getFolderInfo) request. You can change this behavior by changing the request type to getFolderInfo (You get additional info about the containing folder), or by using the setFields() method with an array of all the fields you will be using (You need to add things such as name, etc... as once fields are sent the server will limit it to the fields provided and mandatory fields such as id ).

**Comment by niranjansheshadri** [comment]
Thanks @doncung. I resolved the issue from your solution.
