### ISSUE TITLE
Incompatible with AppCompat v23

### ISSUE THREAD

**Issue by MariusVolkhart** [box/box-android-sdk#27]
The SDK references colors from the AppCompat library. With version 23 of AppCompat, those colors are no longer available so a project using the SDK cannot compile.

Switching to `targetSdkVersion 23` requires using AppCompat v23, so this issue is blocking SDK users from targeting the latest version of Android.

**Comment by doncung** [comment]
Thanks. I've switched to hardcoding the values so you shouldn't get compile errors anymore.
