### ISSUE TITLE
Inconsistencies between Box Content SDKs for Android and iOS

### ISSUE THREAD

**Issue by woodcog** [box/box-android-sdk#276]
For iOS there are error messages to indicate insufficient storage (507) and rate limit exceeded (429), but these errors are not provided in the Content SDK for Android. It would be expected that these errors should be returned for Android too.

Is there is a plan to add these, or can this be requested for a future release?

Source code references:

IOS
https://github.com/box/box-ios-sdk/blob/master/BoxContentSDK/BoxContentSDK/BOXContentSDKErrors.h
BOXContentSDKErrors.h
BOXContentSDKAPIErrorTooManyRequests = 429, // rate limit exceeded
BOXContentSDKAPIErrorInsufficientStorage = 507

ANDROID
https://github.com/box/box-android-sdk/blob/master/box-content-sdk/src/main/java/com/box/androidsdk/content/BoxException.java
BoxException.java 
ErrorType - no error for insufficient storage or rate exceeded

**Comment by doncung** [comment]
The abdroid sdk returns the error directly from the server without
differentiation except for a select few cases. The errors we specifically
handle are usually either special cases(logout type scenarios) or are cases
where we don't get a server response(connection loss). Are you unable to
get the error code or message from the exception?

**Comment by woodcog** [comment]
Hi @doncung, we're unable to trigger the errors for 429 and 507. Can you please provide the exact messages that are returned for these errors. Thank you.

**Comment by doncung** [comment]
The message for 507 should be "Insufficient Storage". As for 429, I believe we handle an exponential backoff/retry by default in the sdk. I'm not sure the server will actually return a message in this situation so we really only check the error code. If the server continues to fail after we retry too many times we will throw:
BoxException.RateLimitAttemptsExceeded("Max attempts exceeded", mNumRateLimitRetries, response);

**Comment by woodcog** [comment]
Thank you @doncung for the error message details.
