### ISSUE TITLE
"Uploading to Box" message on Authentication

### ISSUE THREAD

**Issue by minaEweida** [box/box-android-sdk#284]
I am getting a message "Authenticating.... Uploading to Box" when the Box SDK authentication UI starts to load, however, there is not intention in my code that I am authenticating to upload anything. Is there a way to fix the message showing in pop up? or is there a config that I should do so that it does not display "Uploading to Box" message?

**Comment by doncung** [comment]
Hi Mina, I am unable to find the "Uploading to Box" string anywhere in our SDK. It's possible there is some kind of resource generation issue that is causing that message to show our maybe some other application on your device? Try doing a clean of your project. Possibly you may also want to try doing a find in path for that string to see where it is coming from.

**Comment by minaEweida** [comment]
Hi @doncung, Turns out there was an old message in the strings file that had the same name, so it was overriding the one in the SDK. Thank you very much for looking into it.
