### ISSUE TITLE
setSessionAuthListener doesn't update the listener

### ISSUE THREAD

**Issue by MaksimDmitriev** [box/box-android-sdk#285]
Hello,

1. I downloaded [box-android-sdk](https://github.com/box/box-android-sdk), moved all the Box business logic to a retained fragment.
2. Then I created SecondActivity to start it from MainActivity.
3. SecondActivity has a 'Log out' button.
4. I started the app and logged in to Box. Then I started SecondActivity and logged out there.

For some reason the retained fragment attached to MainActivity got a `BoxAuthentication.AuthListener#onLoggedOut` event. However, I called `mSession.setSessionAuthListener(this);` before calling `logOut()`.

Here is my commit:

https://github.com/MaksimDmitriev/box-android-sdk/commit/96c5cf3e8cb0d19e9f243ef88f9209906c614372

**Comment by doncung** [comment]
Thanks. I've made a fix for this issue here:
https://github.com/box/box-android-sdk/pull/288

**Comment by doncung** [comment]
4.0.9 includes the fix.
