### ISSUE TITLE
Method getSize() return null for all files

### ISSUE THREAD

**Issue by fiasko131** [box/box-android-sdk#290]
My code :
         
               ` for (BoxItem bItem : boxListItems){
                    if (bItem instanceof BoxFile) {
                        BoxFile bFile = (BoxFile) bItem;
                        isDir = false;
                        name = bFile.getName();
                        ext = bFile.getExtension();
                        poid = bFile.getSize();
                        id = bFile.getId();
                        Log.i("BOXSIZE",String.valueOf(bFile.getSize()));
                        if (poid == null){
                            poid = 0L;
                        }
                    
                    } else if (bItem instanceof BoxFolder) {
                        BoxFolder bFolder = (BoxFolder) bItem;
                        isDir = true;
                        name = bFolder.getName();
                        id = bFolder.getId();
                      
                    }

                }`
Others infos are ok.

Thank you for your help.

**Comment by doncung** [comment]
I'm guessing you are having a similar issue as this:
https://github.com/box/box-android-sdk/issues/268

**Comment by doncung** [comment]
Since issue 268 getFolderInfo returns similar results to folder items. You will basically need to add a list of fields to your request that includes BoxItem.FIELD_SIZE. The list will need to include ALL fields you will be interested in (those not included except for a few mandatory fields will not be returned). I do recommend keeping the list to the minimum necessary though since certain fields make the request slower.

**Comment by fiasko131** [comment]
Thanks for reply,

I had already solved my problem like this :
`BoxListItems boxListItems = mFolderApi.getItemsRequest(mId)
                        .setFields(BoxFile.FIELD_SIZE
                                ,BoxFile.FIELD_EXTENSION
                                ,BoxFile.FIELD_ID
                                ,BoxFile.FIELD_PARENT
                                ,BoxFile.FIELD_NAME
                                ,BoxFile.FIELD_PATH_COLLECTION
                                ,BoxFolder.FIELD_ID
                                ,BoxFolder.FIELD_PARENT).send();`
Regards.
