### ISSUE TITLE
No information indicating that I signed in using SSO

### ISSUE THREAD

**Issue by MaksimDmitriev** [box/box-android-sdk#291]
Hello,

I can sign in with SSO provided by my company or my personal login and password. `AuthListener.onAuthCreated` is called in both cases. Is there a flag or something in `BoxAuthentication.BoxAuthenticationInfo` that indicates that I used SSO? 

I looked through `mJsonObject` and didn't find something like `"auth_type":"sso"`

**Comment by doncung** [comment]
No we don't differentiate between sso and normal login. You can check if a
user is part of an enterprise, but login security is based on their
enterprise admin.

**Comment by MaksimDmitriev** [comment]
@doncung how can I can check if a user is part of an enterprise?

**Comment by doncung** [comment]
There is an enterprise object associated with the user. You can get the
current user via user api call. Newer versions of the SDK will include this
in the authinfo at login, but the older versions did not add these fields.

**Comment by MaksimDmitriev** [comment]
@doncung 

> You can get the current user via user api call.

Do you mean `BoxAuthenticationInfo.getUser()`?
Can I get the enterprise object via an API call?

**Comment by doncung** [comment]
There is a chance that you can get the enterprise object from that if a user has logged in via the latest sdk. However for a more reliable way of doing this you will want to use BoxApiUser's getCurrentUserInfoRequest method. You will need to add BoxUser.FIELD_ENTERPRISE as a field in the request in addition to any other data you want to know about the user.
