### ISSUE TITLE
user avatar url not working

### ISSUE THREAD

**Issue by rupbhangale** [box/box-android-sdk#310]
Hi,

I am building the android application using box-content-sdk.
before 2 months Avatar_url which i got from user object after successfully authentication was working fine, but it gives " Error : Too many follow-up requests: 21 " now.
As per my assumption the error occurred as there are more than 20 redirects when calling an endpoint

Can you please help.

**Comment by doncung** [comment]
The user avatar url from the object is deprecated. Please use the
BoxAvatarView or getDownloadAvatarRequest in BoxApiUser.

**Comment by rupbhangale** [comment]
It works.
Thanks...:)
