### ISSUE TITLE
Multi Account for File Upload via Async Task

### ISSUE THREAD

**Issue by Ankurjain30** [box/box-android-sdk#321]
As per below 

BoxSession session = new BoxSession(context, null);
session.authenticate();

i can use multiple logins, but suppose if I have two source folders and two logins are done. how can I send files from one source folder to one login selected folder and similarly for another source folder to the second login.

Is this possible?

Like Personal Box Login > Connected Source Folder > Personal
Official Box Login > Connected Source Folder > Official

**Comment by doncung** [comment]
You would need to collaborate the folders to share content between two different accounts. You could then move/copy the files before removing the collaboration. Otherwise you'd need to download and upload the content since the accounts are logically separated.

**Comment by PreciselyAlyss** [comment]
Closing. Please reopen if you have further questions on this issue.
