### ISSUE TITLE
Can't upload File 

### ISSUE THREAD

**Issue by UmeshBaldaniya46** [box/box-android-sdk#331]
Hello All

I have integrate BOX SDK for Android

i have success fully upload file code
but problem is here same file upload some time or not

private void initBoxSession() {

        mSession = new BoxSession(this);
        mSession.setSessionAuthListener(new BoxAuthentication.AuthListener() {
            @Override
            public void onRefreshed(BoxAuthentication.BoxAuthenticationInfo info) {
                Log.d(TAG, "on refreshed = " + info.accessToken());
            }

            @Override
            public void onAuthCreated(final BoxAuthentication.BoxAuthenticationInfo info) {

                Log.d(TAG, "on auth created = " + info.accessToken());
                Log.d(TAG, "login email  = " + info.getUser().getLogin());
                if (mSession != null && mSession.getAuthInfo() != null && mSession.getAuthInfo().getClientId() != null) {
                    BOXShare boxShare = new BOXShare(context, isPdf, selectedShareFiles, mSession);
                    boxShare.Share();
                } else {
                    Log.e(TAG, "11BOX33");
                }
            }

            @Override
            public void onAuthFailure(BoxAuthentication.BoxAuthenticationInfo info, Exception ex) {

                Log.d(TAG, "authentication of box failed" + ex.getMessage());
                Toast.makeText(context, "authentication failed of BOX!", Toast.LENGTH_SHORT).show();
                ex.printStackTrace();
            }

            @Override
            public void onLoggedOut(BoxAuthentication.BoxAuthenticationInfo info, Exception ex) {
                Log.d(TAG, "on logged out = " + info.accessToken());
            }
        });

        mSession.authenticate(this);

    }

` BoxApiFolder mFolderApi = new BoxApiFolder(mSession);
                    BoxApiFile mFileApi = new BoxApiFile(mSession);

                    for (int i = 0; i < totalFilesUri.size(); i++) {

                        Log.e(TAG, "totalFilesUri  " + totalFilesUri.get(i));

                        File boxFile = new File(totalFilesUri.get(i).getPath());
                        BoxRequestsFile.UploadFile uploadedFile = mFileApi.getUploadRequest(boxFile, "0");
                        final BoxFile uploadFileInfo;
                        try {

                            uploadFileInfo = uploadedFile.send();
                            Log.e(TAG, "uploadFileInfo  " + uploadFileInfo);

                        } catch (BoxException e) {
                            e.printStackTrace();
                        }
                    }`

this code work for some file or nor

//// this for not upload
totalFilesUri  file:///storage/emulated/0/SpeedyScan/aaa/24 15:48:18.pdf
com.box.androidsdk.content.BoxException: An error occurred while sending the request
   at com.box.androidsdk.content.requests.BoxRequest.onSend(BoxRequest.java:243)
 at com.box.androidsdk.content.requests.BoxRequest.send(BoxRequest.java:190)

//// this Upload success
totalFilesUri  file:///storage/emulated/0/SpeedyScan/Doc 2017-24-Nov 15:47:55.pdf
uploadFileInfo  com.box.androidsdk.content.models.BoxFile@fe179d4c

i can't fixed it please help me.

thanks
Umesh...

**Comment by doncung** [comment]
The only think I can think of is the problem is either related to the content of that particular file, or it is some type of timing issue. Make sure you are seeing the full logs. You can configure that by setting BoxConfig.IS_DEBUG to true. That should give you the actual response from the server as to why it is failing. There are many possibilities such as the server is rate limiting or maybe the connection is being disconnected.
