### ISSUE TITLE
Box says that the protocol isn't supported

### ISSUE THREAD

**Issue by mvysny** [box/box-android-sdk#341]
Thank you for a very well documented API and the Android SDK - very useful!

I am able to launch the Box authentication mechanism, with the following redirect URI: `pfbox3209472://oauth`. The `AndroidManifest.xml` contains the Intent filter such as:
```
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="pfbox3209472" />
            </intent-filter>
```
So technically it should work. However, it doesn't: after successful auth, Box SDK shows the following toast: "-10 the protocol isn't supported".

I've made sure that the same redirect URI is configured in the `developer.box.com` page. What should I do please? Could it be that custom schemes are unsupported on Android?

**Comment by doncung** [comment]
Yes the webview will treat a custom scheme as an exception. There is a work around where you can override the exception logic to catch this before the webview shows the toast. I believe the redirect parsing still happens first so you will still be able to login after the toast.

I believe this is may be the same issue as: https://github.com/box/box-android-sdk/issues/277

**Comment by mvysny** [comment]
Thank you for the response. Could you please give a pointer on how to override the exception logic in the webview please, from the `BoxSession` object?

**Comment by doncung** [comment]
Unfortunately you will need to either clone the sdk and modify the OauthActivity class which has an onAuthFailure method. 
You can also extend this activity override this method, and then override the startAuthenticationUI method inside of your session to launch your activity instead.

**Comment by PreciselyAlyss** [comment]
Please reopen if you have any further questions on this issue. 😄
