### ISSUE TITLE
Cancel File Download Request 

### ISSUE THREAD

**Issue by rohitsharma181589** [box/box-android-sdk#347]
Hi 

I want to cancel the download file process in between but can't find any inputs to close it.
Please help me to implement this.

My code is : 
 BoxRequestsFile.DownloadFile downloadFile = boxHealthHelper.getBoxApiFile().getDownloadRequest(file, item.getId());
                        downloadFile.setProgressListener(new ProgressListener() {
                            @Override
                            public void onProgressChanged(long numBytes, long totalBytes) {
                                // Update a progress bar.
                                setDownloadProgress((int) ((numBytes * 100) / totalBytes));
                                if (numBytes == totalBytes)
                                    setResult(file);
                            }
                        });
                        downloadFile.send();

Regards

**Comment by doncung** [comment]
If you want to cancel, I'd suggest using the toTask() method instead of the send method. There is a cancel method there which will interrupt the transfer if it is still in progress. Though it is not guaranteed if the transfer is close to finishing.
