### ISSUE TITLE
There isn't chunk upload api and download part file? 

### ISSUE THREAD

**Issue by kbboss** [box/box-android-sdk#381]
How to download part file?

**Comment by doncung** [comment]
There is a range you can add for downloads.

For uploads there is upload sessionlogic, but only for files larger than 20
MB.

**Comment by kbboss** [comment]
@doncung I found the chunk upload api,but download part not found

**Comment by doncung** [comment]
It is the normal download. The request just takes an additional range which
lets you download a certain part.

**Comment by nidoran** [comment]
@kbboss Here is an example of how to specify a range for the download request:
```
BoxApiFile fileApi = new BoxApiFile(session);
BoxDownload fileDownload = fileApi.getDownloadRequest(file, "fileId")
        // Optional: Set a listener to track download progress.
        .setProgressListener(new ProgressListener() {
            @Override
            public void onProgressChanged(long numBytes, long totalBytes) {
                // Update a progress bar, etc.
            }
        })
        .setRange(100,200)
        .send();
```
