### ISSUE TITLE
Authentication Failed, Contact admin to authorize this device (dup of #318)

### ISSUE THREAD

**Issue by EarlyWild** [box/box-android-sdk#383]
I am encountering the same problem as issue #318 using the latest code (4.2.0). The sample app provided is also throwing this error. I have attached the logcat for the error.

`08-07 14:47:19.389 20319-21597/com.mobile W/System.err: java.util.concurrent.ExecutionException: com.box.androidsdk.content.BoxException: An error occurred while sending the request
08-07 14:47:19.390 20319-21597/com.mobile W/System.err:     at java.util.concurrent.FutureTask.report(FutureTask.java:93)
        at java.util.concurrent.FutureTask.get(FutureTask.java:163)
        at com.box.androidsdk.content.auth.OAuthActivity$3.run(OAuthActivity.java:388)
    Caused by: com.box.androidsdk.content.BoxException: An error occurred while sending the request
        at com.box.androidsdk.content.requests.BoxRequest.onSend(BoxRequest.java:246)
        at com.box.androidsdk.content.requests.BoxRequest.send(BoxRequest.java:193)
        at com.box.androidsdk.content.auth.BoxAuthentication$2.call(BoxAuthentication.java:357)
        at com.box.androidsdk.content.auth.BoxAuthentication$2.call(BoxAuthentication.java:350)
08-07 14:47:19.391 20319-21597/com.mobile W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)`

**Comment by doncung** [comment]
Is this happening for all accounts for you, or only specific accounts? The issue in 318 was caused by trying to call getUsers on accounts that had historically used tags (in which we added the tag field). 
I believe that should no longer be the case since we are no longer asking for those fields. 
If this is account specific please enable both logging and debug in BoxConfig via the IS_DEBUG booleans (default false) and post the detailed messages you are seeing (you may need to look at verbose).

**Comment by EarlyWild** [comment]
Unfortunately, it is happening to all accounts, and I am able to log in successfully through the Box app.
The failure message appears after the user gives the okay for my app to access their box. I have enabled logging and debug. Logcat is below:

`08-08 10:58:57.471 32753-801/com.mobile I/BoxContentSdk: Request (POST):  https://api.box.com/oauth2/token
08-08 10:58:57.472 32753-801/com.mobile I/BoxContentSdk: Request Header:  User-Agent:com.box.sdk.android/4.2.0
08-08 10:58:57.473 32753-801/com.mobile I/BoxContentSdk: Request Header:  Accept-Encoding:gzip
08-08 10:58:57.474 32753-801/com.mobile I/BoxContentSdk: Request Header:  Accept-Charset:utf-8
08-08 10:58:57.475 32753-801/com.mobile I/BoxContentSdk: Request Header:  Content-Type:application/x-www-form-urlencoded
08-08 10:58:57.476 32753-801/com.mobile I/BoxContentSdk: Request Form Data:  code:DeEf9YatH3E5KQCnzXqqy1Ff147MUVZT
08-08 10:58:57.477 32753-801/com.mobile I/BoxContentSdk: Request Form Data:  grant_type:authorization_code
08-08 10:58:57.478 32753-801/com.mobile I/BoxContentSdk: Request Form Data:  client_secret:MYCLIENTSECRET
08-08 10:58:57.479 32753-801/com.mobile I/BoxContentSdk: Request Form Data:  client_id:MYCLIENTID
08-08 10:58:57.484 32753-801/com.mobile I/BoxContentSdk: Response (400):  {"error":"unauthorized_client","error_description":"The grant type is unauthorized for this client_id"}
08-08 10:58:57.493 32753-800/com.mobile W/System.err: java.util.concurrent.ExecutionException: com.box.androidsdk.content.BoxException: An error occurred while sending the request
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
        at com.box.androidsdk.content.auth.OAuthActivity$3.run(OAuthActivity.java:388)
08-08 10:58:57.494 32753-800/com.mobile W/System.err: Caused by: com.box.androidsdk.content.BoxException: An error occurred while sending the request
        at com.box.androidsdk.content.requests.BoxRequest.onSend(BoxRequest.java:246)
        at com.box.androidsdk.content.requests.BoxRequest.send(BoxRequest.java:193)
        at com.box.androidsdk.content.auth.BoxAuthentication$2.call(BoxAuthentication.java:357)
        at com.box.androidsdk.content.auth.BoxAuthentication$2.call(BoxAuthentication.java:350)
08-08 10:58:57.495 32753-800/com.mobile W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)`

Maybe it is how I am authenticating? This is how I am doing it:

`       BoxConfig.CLIENT_ID = "MYCLIENTID"
        BoxConfig.CLIENT_SECRET = "MYSECRETKEY"
        BoxConfig.IS_DEBUG = true
        BoxConfig.IS_LOG_ENABLED = true
        val session = BoxSession(this)
        session.setSessionAuthListener(this)
        session.authenticate(this)`

Also, my app is completely written in kotlin (but I do not think that should matter)

**Comment by doncung** [comment]
Based on the message it may be based on how your api key is setup.
Can you tell me what settings you have? I suspect you are using the jwt
option in which case it would make sense for web based login to fail.

**Comment by EarlyWild** [comment]
I am using the jwt option. I am have never worked with jwt. Does it require the Box app to be installed?

**Comment by EarlyWild** [comment]
I have also tried using the "Standard Oauth 2.0" with a rediect URI to "https://localhost". Here is my code...

        BoxConfig.CLIENT_ID = "MYCLIENTID"
        BoxConfig.CLIENT_SECRET = "MYSECRETKEY"
        BoxConfig.IS_DEBUG = true
        BoxConfig.IS_LOG_ENABLED = true
        BoxConfig.REDIRECT_URL = "https://localhost"
        val session = BoxSession(this)
        session.setSessionAuthListener(this)
        session.authenticate(this)

Which produces the following error (I have modified some stuff to hide sensitive information)

08-08 14:18:53.191 10028-10454/com.mobile I/BoxContentSdk: Request (POST):  https://api.box.com/oauth2/token
08-08 14:18:53.194 10028-10454/com.mobile I/BoxContentSdk: Request Header:  User-Agent:com.box.sdk.android/4.2.0
08-08 14:18:53.196 10028-10454/com.mobile I/BoxContentSdk: Request Header:  Accept-Encoding:gzip
08-08 14:18:53.200 10028-10454/com.mobile I/BoxContentSdk: Request Header:  Accept-Charset:utf-8
08-08 14:18:53.203 10028-10454/com.mobile I/BoxContentSdk: Request Header:  Content-Type:application/x-www-form-urlencoded
08-08 14:18:53.206 10028-10454/com.mobile I/BoxContentSdk: Request Form Data:  code:RSkE68rPzFLwXtOzCkmZ15bCF5ut
08-08 14:18:53.209 10028-10454/com.mobile I/BoxContentSdk: Request Form Data:  grant_type:authorization_code
08-08 14:18:53.212 10028-10454/com.mobile I/BoxContentSdk: Request Form Data:  client_secret:MYSECRETKEY
08-08 14:18:53.215 10028-10454/com.mobile I/BoxContentSdk: Request Form Data:  MYCLIENTID
08-08 14:18:53.228 10028-10454/com.mobile I/BoxContentSdk: Response (200):  {"access_token":"6XmFcXeUxq7QBoiDjlbKKGFVsr7L","expires_in":4241,"restricted_to":[],"refresh_token":"InGcji7dw1Yd7621s5u6NuHfaX9zrNJShKSWD2p6NDvGRTSS1ol","token_type":"bearer"}
08-08 14:18:53.602 10028-10454/com.mobile I/BoxContentSdk: Request (GET):  https://api.box.com/2.0/users/me?fields=type%2Cid%2Cname%2Clogin%2Cspace_amount%2Cspace_used%2Cmax_upload_size%2Cstatus%2Centerprise%2Ccreated_at
08-08 14:18:53.607 10028-10454/com.mobile I/BoxContentSdk: Request Header:  Authorization:Bearer 6XmFcXeUxq7QBGtgaoiDjlbKKGFVsr7L
08-08 14:18:53.610 10028-10454/com..mobile I/BoxContentSdk: Request Header:  User-Agent:com.box.sdk.android/4.2.0
08-08 14:18:53.614 10028-10454/com.mobile I/BoxContentSdk: Request Header:  Accept-Encoding:gzip
08-08 14:18:53.618 10028-10454/com.mobile I/BoxContentSdk: Request Header:  Accept-Charset:utf-8
08-08 14:18:53.622 10028-10454/com.mobile I/BoxContentSdk: Request Header:  Content-Type:application/json
08-08 14:18:53.633 10028-10454/com.mobile I/BoxContentSdk: Response (200):  {"type":"user","id":"256966","name":"qid sid","login":"qid@gmail.com","space_amount":53687091200,"space_used":2160074428,"max_upload_size":262144000,"status":"active","enterprise":null,"created_at":"2013-12-30T11:02:43-08:00"}
08-08 14:18:53.669 10028-10454/com.mobile E/trying to modify ImmutableBoxAuthenticationInfo: java.lang.RuntimeException
        at com.box.androidsdk.content.auth.BoxAuthentication$BoxAuthenticationInfo$BoxImmutableAuthenticationInfo.createFromJson(BoxAuthentication.java:784)
        at com.box.androidsdk.content.models.BoxJsonObject.<init>(BoxJsonObject.java:37)
        at com.box.androidsdk.content.auth.BoxAuthentication$BoxAuthenticationInfo.<init>(BoxAuthentication.java:601)
        at com.box.androidsdk.content.auth.BoxAuthentication$BoxAuthenticationInfo$BoxImmutableAuthenticationInfo.<init>(BoxAuthentication.java:768)
        at com.box.androidsdk.content.auth.BoxAuthentication$BoxAuthenticationInfo.unmodifiableObject(BoxAuthentication.java:760)
        at com.box.androidsdk.content.auth.BoxAuthentication.onAuthenticated(BoxAuthentication.java:159)
        at com.box.androidsdk.content.auth.BoxAuthentication$2.call(BoxAuthentication.java:368)
        at com.box.androidsdk.content.auth.BoxAuthentication$2.call(BoxAuthentication.java:350)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
08-08 14:18:53.772 10028-10453/com.mobile W/System.err: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
08-08 14:18:53.773 10028-10453/com.mobile W/System.err:     at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
08-08 14:18:53.774 10028-10453/com.mobile W/System.err:     at com.box.androidsdk.content.auth.OAuthActivity$3.run(OAuthActivity.java:388)
08-08 14:18:53.777 10028-10453/com.mobile W/System.err: Caused by: java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
        at android.widget.Toast$TN.<init>(Toast.java:463)
08-08 14:18:53.778 10028-10453/com.mobile W/System.err:     at android.widget.Toast.<init>(Toast.java:131)
        at android.widget.Toast.makeText(Toast.java:343)
08-08 14:18:53.779 10028-10453/com.mobile W/System.err:     at android.widget.Toast.makeText(Toast.java:333)
        at com.mobile.activities.Documents.BoxFilesActivity.onAuthCreated(BoxFilesActivity.kt:55)
08-08 14:18:53.780 10028-10453/com.mobile W/System.err:     at com.box.androidsdk.content.models.BoxSession.onAuthCreated(BoxSession.java:585)
        at com.box.androidsdk.content.auth.BoxAuthentication.onAuthenticated(BoxAuthentication.java:171)
08-08 14:18:53.781 10028-10453/com.mobile W/System.err:     at com.box.androidsdk.content.auth.BoxAuthentication$2.call(BoxAuthentication.java:368)
08-08 14:18:53.782 10028-10453/com.mobile W/System.err:     at com.box.androidsdk.content.auth.BoxAuthentication$2.call(BoxAuthentication.java:350)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-08 14:18:53.783 10028-10453/com.mobile W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-08 14:18:53.784 10028-10453/com.mobile W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
08-08 14:18:53.785 10028-10453/com.mobile W/System.err:     at java.lang.Thread.run(Thread.java:764)
08-08 14:18:53.990 10028-10028/com.mobile E/NON_FATALBoxAuthfail: failure:auth storage :com.box.androidsdk.content.auth.BoxAuthentication$AuthStorage@97047b1

**Comment by doncung** [comment]
Ok, so looks like the jwt option was the main issue. That is used for our app user functionality in which case you will need to build out your own server infrastructure to identify your users with box users (basically your jwt token will reside on your server side and is used to provision and authenticate new app user accounts). It would require calling custom server logic to do refreshing and authenticating, but allows developers to have their own user sign up and login logic.

After switching it looks like it is working as expected, but you have some kind of toast here:
at com.mobile.activities.Documents.BoxFilesActivity.onAuthCreated(BoxFilesActivity.kt:55)

Our listeners are not called on a separate thread, and so hopefully once removed everything should work.

**Comment by EarlyWild** [comment]
Okay. Thank you for clarifying the jwt option. As for the toast message, it is kinda weird because I only have 43 lines of code in that file (see below)

`package com.mobile.activities.Documents

import android.support.v7.app.AppCompatActivity
import android.os.Bundle
import com.box.androidsdk.content.BoxConfig
import com.box.androidsdk.content.auth.BoxAuthentication
import com.mobile.R
import com.box.androidsdk.content.models.BoxSession
import org.jetbrains.anko.toast
import java.lang.Exception


class BoxFilesActivity : AppCompatActivity(), BoxAuthentication.AuthListener {
    override fun onLoggedOut(info: BoxAuthentication.BoxAuthenticationInfo?, ex: Exception?) {
        toast("LOGGED OUT")
    }

    override fun onAuthCreated(info: BoxAuthentication.BoxAuthenticationInfo?) {
        toast("AUTH CREATED")
    }

    override fun onRefreshed(info: BoxAuthentication.BoxAuthenticationInfo?) {
        toast("AUTH REFRESHED")
    }

    override fun onAuthFailure(info: BoxAuthentication.BoxAuthenticationInfo?, ex: Exception?) {
        toast("AUTH FAILED")
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_box_files)

        BoxConfig.CLIENT_ID = "MYCLIENTID"
        BoxConfig.CLIENT_SECRET = "MYCLIENTSECRET"
        BoxConfig.IS_DEBUG = true
        BoxConfig.IS_LOG_ENABLED = true
        BoxConfig.REDIRECT_URL = "https://localhost"
        val session = BoxSession(this)
        session.setSessionAuthListener(this)
        session.authenticate(this)
    }
}
`
Box is failing to authenticate though. First there is a runtime exception

> 08-08 17:18:30.887 4696-4921/com.printeron.mobile E/trying to modify ImmutableBoxAuthenticationInfo: java.lang.RuntimeException
>         at com.box.androidsdk.content.auth.BoxAuthentication$BoxAuthenticationInfo$BoxImmutableAuthenticationInfo.createFromJson(BoxAuthentication.java:784)
>         at com.box.androidsdk.content.models.BoxJsonObject.<init>(BoxJsonObject.java:37)
>         at com.box.androidsdk.content.auth.BoxAuthentication$BoxAuthenticationInfo.<init>(BoxAuthentication.java:601)
>         at com.box.androidsdk.content.auth.BoxAuthentication$BoxAuthenticationInfo$BoxImmutableAuthenticationInfo.<init>(BoxAuthentication.java:768)
>         at com.box.androidsdk.content.auth.BoxAuthentication$BoxAuthenticationInfo.unmodifiableObject(BoxAuthentication.java:760)
>         at com.box.androidsdk.content.auth.BoxAuthentication.onAuthenticated(BoxAuthentication.java:159)
>         at com.box.androidsdk.content.auth.BoxAuthentication$2.call(BoxAuthentication.java:368)
>         at com.box.androidsdk.content.auth.BoxAuthentication$2.call(BoxAuthentication.java:350)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
>         at java.lang.Thread.run(Thread.java:764)

then the auth failure:

> 08-08 17:18:31.128 4696-4696/com.printeron.mobile E/NON_FATALBoxAuthfail: failure:auth storage :com.box.androidsdk.content.auth.BoxAuthentication$AuthStorage@7c22c70

I'm really stumped on what I am doing incorrectly. Also, when I re-enter the activity second time (after the failure), it does not prompt for authorization nor are there any account information for any user.

**Comment by doncung** [comment]
So the reason it doesn't prompt the second time is because the user should already be authenticated.
As such you can use it as is to make api calls after using it to construct a BoxApi object.
Looking at your logs, the crash last time was happening right after login was successful and so the SDK remembers the last authenticated user and so as soon as you constructed BoxSession(this) it already had valid auth info. The authenticate call later does nothing since it detects there is already valid information (you can add a listener to the task returned in the authenticate call).

The previous crash is caused by the toast logic which needs to be run on the UI thread not being run on the UI thread. Try replacing toast with a "Sytem.out.println"which doesn't have that requirement and clearing the data in your sample app. Then you should be able to login.

**Comment by EarlyWild** [comment]
Awesome! Thank you for your help with this. I have got it working.
