### ISSUE TITLE
totalBytes is 0 when uploading file via InputStream

### ISSUE THREAD

**Issue by ka05** [box/box-android-sdk#401]
### Description of the Issue

When uploading a file via an inputStream in the progress listener callback the totalBytes is always 0. The only way to fix this is to `setUploadSize(filesize)` passing in the filesize calculated from the inputStream.

Since the InputStream is passed into the getUploadReguest method the box sdk should set the upload size automatically in that method since it has access to the stream passed in as an argument. To get the filesize use: `uploadStream.available()`

### Versions Used
Box Content SDK: 4.2.0
Android: 9.0

**Comment by nidoran** [comment]
@ka05 
In general it is not possible to know an InputStream's total length before reading the entire stream has completed.
`public int available() throws IOException` on `InputStream` is not going to always return the stream's total length.
