### ISSUE TITLE
Issues with SDK v4.0.11(also 4.2.3) while using Android SDK 28 

### ISSUE THREAD

**Issue by sagarall** [box/box-android-sdk#408]
Hi BOX team,

The current BOX content SDK version that is used in our app is “4.0.11”. There are some build issues when we update our Android SDK version to 28, due to some deprecated classes in com.box.androidsdk.content.views.BezelImageView.java (Canvas.HAS_ALPHA_LAYER_SAVE_FLAG and Canvas.FULL_COLOR_LAYER_SAVE_FLAG)
 
The latest release version of content SDK “4.2.3” has the same problem. Can you please tell us when you will be releasing the “5.0.0” version of the content SDK, as i have seen you have updated your Android version to 28 in this version and took care of the above issue too.

Please let you me know the timeline for your “5.0.0” version, so that we can plan our updates accordingly. Also if possible, please share the guidelines/steps to update BOX content SDK.

Thanks.

**Comment by lupajz** [comment]
Version 5.0.0 is already out available at maven https://search.maven.org/artifact/com.box/box-android-sdk/5.0.0/aar
