### ISSUE TITLE
Download converted file - representation is always null

### ISSUE THREAD

**Issue by kotoMJ** [box/box-android-sdk#414]
### Description of the Issue
When I try to obtain representations for com.box.androidsdk.content.models.Boxfile then representations field is always null. 
My intention is to get specific representation [pdf] of the file uploaded to box [docx, txt] in order to use in com.box.androidsdk.content.BoxApiFile.getDownloadRepresentationRequest later on. 

### Versions Used
box-android-sdk:4.2.0

### Steps to Reproduce
1) Firstly I get BoxApiFile() initialised with proper session parameter.
2) Then I request BoxFile object via. boxApiFile.getInfoRequest(fileId).toTask()
3) Then I run this task and wait for an object
4) But resulting BoxFile has always **null field** called **representations**

[api-docs]: https://community.box.com/t5/Platform-and-Development-Forum/Box-android-sdk-download-converted-file/m-p/76681#M7158

**Comment by doncung** [comment]
You need to specifically add the representations field to the info request. Otherwise it will always come in as null. Also the representation may not necessarily have started creation yet so one of the calls in the reps object will start the conversion.

**Comment by PJSimon** [comment]
Hi @kotoMJ, 

I'm going to close this issue, assuming you're all set.  If not, by all means, please go ahead and re-open it and we'll go from there.  Thanks!

Patrick

**Comment by kotoMJ** [comment]
Hey @PJSimon thank you for letting me know. Currently I am out of the project, where we had that issue. And I believe my colleagues (@JakubGongol) will follow your offer, whenever they will be back to solve this issue. Thanks.
