### ISSUE TITLE
Download specific file version 

### ISSUE THREAD

**Issue by fistuk** [box/box-android-sdk#418]
Im trying to download a specific version of a file. For java SDK it may be done as [follows](https://developer.box.com/en/guides/downloads/file-version/):
```
BoxFile file = new BoxFile(api, "id");
List<BoxFileVersion> versions = file.getVersions();
BoxFileVersion firstVersion = versions.get(0);

FileOutputStream stream = new FileOutputStream(firstVersion.getName());
firstVersion.download(stream);
stream.close();
```

With Android SDK I'm doing the following:
`fileApi.getDownloadRequest(outputStream, id).send()`

Didn't find a way to download a specific version.

**Comment by fistuk** [comment]
Its possible to set version on the download request:
```
fileApi.getDownloadRequest(outputStream, id).setVersion(versionId)
                .setProgressListener { numBytes, totalBytes ->
                  
                }
```

**Comment by PJSimon** [comment]
Hey @fistuk, closing this at it appears you've resolved it.  Thanks for sharing your findings here!  If you need anything else, please feel free to open another issue or re-open this one!

Thanks!
