### ISSUE TITLE
Download progress listener returns invalid totalBytes value

### ISSUE THREAD

**Issue by fistuk** [box/box-android-sdk#419]
While using the download api:
```
fileApi.getDownloadRequest(outputStream, id)
                        .setProgressListener { numBytes, totalBytes ->
                            val progress = numBytes / totalBytes
                        }.send()
```

The totalBytes value returned is always -1. 
Box SDK version: 5.0.0

**Comment by doncung** [comment]
Are you able to add a break point to BoxRequestDownload in the onResponse method? The length comes from the header the api call for "Content-Length". Certain apis such as avatars may not support the header, but I tried on a normal file and did see it. It would be helpful if you can provide the type of file, its size, etc...

**Comment by PJSimon** [comment]
Hi @fistuk, I just wanted to add an @-mention so you could see @doncung 's comment, above.  If that helps you, or you need more help, please let us know!

**Comment by PJSimon** [comment]
Closed by accident!  :^)

**Comment by PJSimon** [comment]
Hopefully you're all set @fistuk!  If not, please feel free to re-open!
