### ISSUE TITLE
How to open/view a BoxFile?

### ISSUE THREAD

**Issue by teferio** [box/box-android-sdk#421]
Hello, 

How do we open/view a BoxFile without Downloading it?

                val intent = Intent(Intent.ACTION_VIEW)
                 intent.setData .......?
                 startActivity(intent)

**Comment by PJSimon** [comment]
Hi @teferio,

I'm not sure I understand what you are asking.

If you just want to view the details of a file without downloading the file contents, you can [Get Info about a Box File](https://github.com/box/box-android-sdk/blob/master/doc/Files.md#get-info-about-a-box-file).
If you want to avoid downloading the **entire file contents** locally, you can download the file using a FileOutputStream ([see the second example here](https://github.com/box/box-android-sdk/blob/master/doc/Files.md#download-a-box-file)).

If that doesn't help, please let me know!

**Comment by PJSimon** [comment]
Hi @teferio,

Just checking in!  Were you able to resolve this?  If so, we can close it.

Thanks!

**Comment by teferio** [comment]
Hi @PJSimon 

Yes, Thanks!
