### ISSUE TITLE
Version 5.0.0 in Maven Central?

### ISSUE THREAD

**Issue by ashughes** [box/box-android-sdk#429]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I noticed that there is a [version `5.0.0` available in Maven Central](https://mvnrepository.com/artifact/com.box/box-android-sdk/5.0.0), but I can't find any references to it anywhere in this repository (in the releases, changelog, branches, etc). The upload date is listed as May 29, **2019**, so I'm guessing it might just be a mistake and you might want to remove it from Maven Central.

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by PJSimon** [comment]
Hi @ReporterGitHubUserName,

Thanks for submitting this Issue! We will take a look and get back to you ASAP!

@PJSimon

**Comment by ashughes** [comment]
@PJSimon Any update on this?

**Comment by mgrytsai** [comment]
[5.0.0 version in maven Central](https://mvnrepository.com/artifact/com.box/box-android-sdk/5.0.0) is a mistake. Please use latest [4.2.3 package](https://github.com/box/box-android-sdk/releases/tag/v4.2.3)

Unfortunately, that's not possible to delete any package from Maven central.
