### ISSUE TITLE
How to get ID of uploaded file?

### ISSUE THREAD

**Issue by DavidVasquezMindstrong** [box/box-android-sdk#434]
Hello

I'm uploading files using the sdk `com.box:box-android-sdk:5.0.0`. After the file has been successfully uploaded, I try to get the file ID but it always returns `null`.

```
        private BoxRequestUpload uploadFile;
        private BoxFutureTask boxFutureTask;

        BoxAuthentication.BoxAuthenticationInfo info = new BoxAuthentication.BoxAuthenticationInfo();
        info.setAccessToken(token);

        BoxSession session = new BoxSession(context, info, null);
        session.authenticate(context, response -> {
            if (response.isSuccess()) {
                try {
                    BoxApiFile fileApi = new BoxApiFile(session);
                    InputStream inputStream = context.getContentResolver().openInputStream(uri);
                    if (!reUpload) {
                        // brand new file upload
                        uploadFile = fileApi.getUploadRequest(inputStream, filename, folderId);
                    } else {
                        // update file version
                        uploadFile = fileApi.getUploadNewVersionRequest(inputStream, existingFileId);
                    }
                    uploadFile.setUploadSize(totalBytes);
                    boxFutureTask = uploadFile.setProgressListener((numBytes, totalBytes) -> {
                       // update progress bar
                    }).toTask();
                    boxFutureTask.run();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
```
After the file is uploaded, I use `uploadFile.getId()`, but this always returns `null`

Can anyone help me to solve how to get the ID of the file?

Thank you

**Comment by sujaygarlanka** [comment]
@DavidVasquezMindstrong I first recommend using the Android SDK version 4.2.3 found [here](https://mvnrepository.com/artifact/com.box/box-android-sdk/4.2.3). I apologize, but version 5.0.0 is a a beta. Also, I recommend trying to a run simple upload command as shown in our docs [here](https://github.com/box/box-android-sdk/blob/fed776db26f2840dc3f52d291eb81b37b66cdb2c/doc/Files.md#upload-a-file). If this works, then I would try doing what you are doing with `BoxFutureTask`.
Also, some sample code can be found here in our sample [app](https://github.com/box/box-android-sdk/blob/fed776db26f2840dc3f52d291eb81b37b66cdb2c/box-content-sample/src/main/java/com/box/androidsdk/sample/MainActivity.java#L150). I hope this helps!

**Comment by DavidVasquezMindstrong** [comment]
Thanks for the response. The samples helped me to get to the solution. I ended up adding a completion listener to the future task

```
boxFutureTask.addOnCompletedListener(boxResponse -> {
     if (boxResponse.isSuccess()) {
          fileId = ((BoxFile) boxResponse.getResult()).getId();
     }
});
```

Thanks again
