### ISSUE TITLE
Are there any updates planned for this repository?

### ISSUE THREAD

**Issue by rpavliuk** [box/box-android-sdk#445]
Do you plan to support this sdk or we need to switch to [java sdk](https://github.com/box/box-java-sdk)?

**Comment by mwwoda** [comment]
Hi @rpavliuk 
Android SDK is currently in maintenance mod, which means only critical issues will be fixed. There is a long-term plan to make the Android SDK api parity improved to the level of our other SDKs, but I can't give you a time frame for when that will happen at this point.

**Comment by rpavliuk** [comment]
@mwwoda Thank for a quick response. We will wait 🙂
