### ISSUE TITLE
Remove appcompat-v7

### ISSUE THREAD

**Issue by isabsent** [box/box-android-sdk#52]
Is it possible to not include com.android.support:appcompat-v7:21.0.3 dependency to your SDK? I have a problem trying to use your SDK with my existing code due to conflict of some parameters (colorAccent) in attrs.xml. Other clouds do not include this library (Dropbox, GoogleDrive, OneDrive) and there are no problems.

**Comment by doncung** [comment]
We'll investigate removing that dependency. I believe it's necessary in our
UI Sdks such as browse, share, and preview but
we might not be relying on it in the content sdk.
In the meantime try including an exclude statement in the line where you
reference the sdk to see if that works for you.
It'll be something like this:
compile project(':box-content-sdk'){
  exclude group: 'com.android.support', module:' appcompat-v7'
}

or if you are just referencing directly from maven:
compile ('com.box:box-android-sdk:3.0.3'){
  exclude group: 'com.android.support', module:' appcompat-v7'
}

**Comment by isabsent** [comment]
I am using your SDK as an external library and have tried to exclude appcompat-v7 by  this way :
compile('com.box:box-android-sdk:3.0.3') { 
    exclude group: 'com.android.support', module:' appcompat-v7' 
}
and this error appears:
E:\IdeaProjects\BestCryptGradle\bestcrypt\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\values\values.xml
Error:(1, -1) Gradle: Attribute "colorAccent" has already been defined

Is it impossible to use your SDK by this way? And what am I doing wrong if it is possible?

**Comment by isabsent** [comment]
The only way a got the success is to remove all appcompat-v7 references from your SDK source code, compile the rest of SDK as aar library and attach it to my project as:

    compile 'libs/com.box:box-android-sdk:3.0.3@aar' 
    compile 'com.eclipsesource.minimal-json:minimal-json:0.9.1'

**Comment by doncung** [comment]
I see thanks. Looks like we're just relying on it for some basic styles. We'll look into duplicating those themes into our SDK so we can remove the dependency.

**Comment by isabsent** [comment]
I had to remove R.layout.support_simple_spinner_dropdown_item  (ChooseAuthenticationFragment.java) too along with TextAppearance.AppCompat.xxx references from my customized aar. There are no other references to appcompat-v7 in your SDK.

**Comment by doncung** [comment]
Thanks. I've removed the dependency on appcompat now.
