### ISSUE TITLE
Add method getInputStream(String fileId) to file download methods.

### ISSUE THREAD

**Issue by isabsent** [box/box-android-sdk#53]
To download file from Box cloud I have two API methods in box-android-sdk: 

    getDownloadRequest([OutputStream | File], String)

I need an InputStream as a result of download request and, therefore, I have to  make some overhead transferring OutputStream back to InputStream because you already made a reverse operation:

    SdkUtils.copyStream(response.getHttpURLConnection().getInputStream(), output);

in BoxRequestDownload class of your SDK. Is it possible to add direct method

    InputStream getInputStream(String fileId) {
        return response.getHttpURLConnection().getInputStream();
    }

to public API?

By the way, you already have presented such method in box-java-sdk:

    URL url = new URL("files/" + file.getID() + "/content")
    BoxAPIRequest request = new BoxAPIRequest(api, url, "GET");
    BoxAPIResponse response = request.send();
    InputStream bodyStream = response.getBody();

**Comment by doncung** [comment]
The reason we didn't want to do that is because we wanted to follow a consistent pattern in the new sdk where the send() methods trigger the api call. We'll take this request into consideration, but we'll need to decide within the team if the confusion is worth the new method.

**Comment by isabsent** [comment]
Thanks for your explatation.

**Comment by andycass** [comment]
Is there any way whatsoever to get an inputStream this would be a super useful feature, Google drive, dropbox and oneDrive all offer simple ways to get an InputStream....

**Comment by isabsent** [comment]
I had been forced to convert their `OutputStram` to an `InputStream` by means of the [EasyStream library](http://io-tools.sourceforge.net/easystream/OutputStream_to_InputStream.html)
with this code;

    InputStreamFromOutputStream<BoxDownload> inputStreamFromOutputStram = new InputStreamFromOutputStream<BoxDownload>() {

        @Override
        public BoxDownload produce(final OutputStream os) throws Exception {
            long fileSize = BoxFile.this.length();
            return service.getDownloadRequest(os, item.getId()).setRange(0, fileSize).send();//Problem with encoding for .txt files without setRange
        }
    };
Looks crazy, but their **"...consistent pattern in the new sdk ..."** does not give us other choice... You can read a little bit more in [this blog](//http://blog.ostermiller.org/convert-java-outputstream-inputstream).

**Be careful** using this EasyStream library. It has open gradle dependecy on `org.slf4j:slf4j-api` which can crash your app. To avoid this I am using 

    def versionOverrides = [
            "org.slf4j:slf4j-api": "1.7.25"
    ]

    configurations.all {
        resolutionStrategy.eachDependency {
            DependencyResolveDetails details ->
                def overrideVersion = versionOverrides[details.requested.group + ":" + details.requested.name]
                if (overrideVersion != null && details.requested.version != overrideVersion) {
                    logger.info "Overriding dependency ${details.requested.group}:${details.requested.name} version ${details.requested.version} --> $overrideVersion"
                    details.useVersion overrideVersion
                }
        }
    }
in the app level `build.gradle`.

**Comment by andycass** [comment]
Thanks isabsent I came across this blog too
 http://blog.ostermiller.org/convert-java-outputstream-inputstream 
and used it to stream music via a piped input stream from the box android sdk, but it is a bit problematic i'm going to try a Circular Buffer and your EasyStream example.

 I also came across this post 
https://github.com/box/box-android-sdk/issues/292

 I'm going to try this too 

Thank you for your reply....

**Comment by isabsent** [comment]
Please, share code sample with Circular Buffer if you get success with it!

**Comment by andycass** [comment]
Will do... Are you trying to stream content isabsent ?

**Comment by isabsent** [comment]
Did not exactly catch what do you mean.

**Comment by 1gravity** [comment]
You can do a simple:
```
        val output = ByteArrayOutputStream()
        api.getDownloadRequest(output, item.id).send()
        return ByteArrayInputStream(output.toByteArray())
```
Not very efficient but my files are small so this is fine. Having a direct method to get an InputStream would be great, as others have mentioned before.
