### ISSUE TITLE
Is it possible to mplement Parcelable interface on your model classes - at least on BoxFolder and BoxFile

### ISSUE THREAD

**Issue by isabsent** [box/box-android-sdk#54]
Is it possible to implement Parcelable interface on your model classes - at least on BoxFolder and BoxFile. It would be very handy because such entities are transferred between activities or services in Android applications very frequently.

**Comment by doncung** [comment]
BoxFolder and BoxFile are serializable so you should be able to use that similarly to parcelable. We've done some performance testing before reaching the decision to use serializable instead of parcelable and found the performance impact wasn't significant enough to justify implementing parcelable.

**Comment by isabsent** [comment]
Thanks for clarifying.
