### ISSUE TITLE
Add new version to repository.

### ISSUE THREAD

**Issue by isabsent** [box/box-android-sdk#62]
Is it possible to put your last SDK version (3.0.4?) to [bintray.com](https://bintray.com/bintray/jcenter/com.box%3Abox-android-sdk/view) in order to make it accessible with Gradle?

**Comment by isabsent** [comment]
Please, update repos to use your SDK with Gradle! There is old version with AppCompat dependencies till now! I had to recompile your code and use custom .aar as a library more than half year!

**Comment by doncung** [comment]
Sorry for the long wait. We've merged the latest to maven now.
