### ISSUE TITLE
Android security alert with latest version

### ISSUE THREAD

**Issue by jefftharris** [box/box-android-sdk#96]
I am receiving a security alert from Google with my app that uses the latest version of the SDK.

From Google:
Your application has an unsafe implementation of the WebViewClient.onReceivedSslError handler. Specifically, the implementation ignores all SSL certificate validation errors, making your app vulnerable to man-in-the-middle attacks. An attacker could change the affected WebView's content, read transmitted data (such as login credentials), and execute code inside the app using JavaScript.
To properly handle SSL certificate validation, change your code to invoke SslErrorHandler.proceed() whenever the certificate presented by the server meets your expectations, and invoke SslErrorHandler.cancel() otherwise.

**Comment by doncung** [comment]
Thanks Jeff. The logic is written to fail on any ssl issues by default.
Only when the config is explicitly set do we show a dialog letting the user
proceed after inspecting the error information. This is to allow some
customers with self signed certs to use the sdk. Can you tell me how you
got this alert? We haven't heard anything from google about this ourselves.

**Comment by jefftharris** [comment]
I cloned the latest master branch in integrated the code into my app, PasswdSafe Sync, and released an update to the Play store.  A few days later, I got this alert in my developer console.

I leave BoxConfig.ALLOW_SSL_ERROR set to its default value of false.  Is there a code path in, presumably OAuthWebView, where the method isn't called on the error?  Is the code allowed to use a dialog and defer the call on the error object vs. making the call in the callback directly?  I've not used the WebViewClient class directly, so I don't know the details of its use.

Google mentions they are going to send an email with details of the issue, but I haven't received one.

**Comment by doncung** [comment]
I am guessing they are automatically decompiling the code and have some
kind of linting rules that trigger these warnings. The flow shouldn't be
hit. For now, can you compile the sdk as a project and just manually delete
that if block with the config?
I need to check with a few people before removing the functionality from
the sdk.

**Comment by jefftharris** [comment]
I can try the manual changes to remove ALLOW_SSL_ERROR.  I'll also always call handler.cancel() before showing the alert dialog.

Looking at the code, I see the dismiss listener doesn't call handler.cancel().  So, there's a code path where the handler doesn't get called.  Maybe they flag that as well. 

Unfortunately I'll have to do a app release before knowing whether the changes fix anything.

**Comment by jefftharris** [comment]
The issue does not appear to be caused by the Box library.  I received the Android alert shortly after upgrading the Box library, and Google hadn't responded with an exact location of the error.  After the update from above, I received another alert with the exact location.  The location was is another library that uses an SSL connection which I hadn't updated.  The security alerts must have been new leading to the apparent Box issue.  A fix in the other library cleared the alert from the app.

Closing the issue as not-applicable.
